/**
 * swamp.lost — Game Texts
 *
 * SINGLE SOURCE OF TRUTH for all player-visible text.
 *
 * To change any in-game text, edit ONLY this file.
 * No HTML, CSS, or JavaScript logic files should contain hardcoded strings.
 *
 * Structure:
 *   - intro:       Start screen texts
 *   - gate:        Gate input / homepage texts
 *   - routes:      Atmospheric route introductions (keyed by station ID)
 *   - irrlichter:  Questions & answers per Irrlicht (keyed by station number)
 *   - decisions:   Follow / go on button labels
 *   - results:     Ending screen texts (keyed by result type)
 *   - ui:          Shared UI labels (buttons, errors, placeholders)
 */

export const GAME_TEXTS = Object.freeze({

  // ─────────────────────────────────────────────
  // START INTRO
  // ─────────────────────────────────────────────
  intro: Object.freeze({
    title: "swamp.lost",
    subtitle:
      "Once there was a forest, now it's a swamp. We used to surf meaning, now it's all slop.",
    mission: Object.freeze([
      "find a dark forest community and exploit them",
      "navigate through the swamp by following the trustworthy Irrlichter",
      "be careful they could be traps",
    ]),
    startButton: "Start your Journey",
  }),

  // ─────────────────────────────────────────────
  // GATE INPUT / HOMEPAGE
  // ─────────────────────────────────────────────
  gate: Object.freeze({
    inputPlaceholder: "Gate ID",
    submitButton: "Enter Gate",
    errorInvalid: "Invalid Gate ID. Access denied.",
  }),

  // ─────────────────────────────────────────────
  // ROUTE PAGES (atmospheric introductions)
  // Keyed by station number (1, 2, 3)
  // ─────────────────────────────────────────────
  routes: Object.freeze({
    1: Object.freeze({
      id: "slop-seas",
      title: "Slop Sea",
      mainText: "You start in the Slop Seas.",
      body: Object.freeze([
        "Open oceans of autogenerated content. Infinite Medium articles. AI-generated reaction videos. Recursive listicles summarizing other recursive listicles.",
        "Most sailors go insane here after prolonged exposure. The danger isn't misinformation. It's cognitive suffocation. You forget what original thought feels like.",
      ]),
    }),
    2: Object.freeze({
      id: "fog-bank",
      title: "Fog Bank",
      mainText: "You arrive at the Fog Banks.",
      body: Object.freeze([
        "Regions saturated by synthetic engagement.",
        "Nothing there is technically fake enough to trigger alarms.",
        "But everything feels slightly wrong.",
        "Too agreeable. Too optimized. Too emotionally calibrated.",
      ]),
    }),
    3: Object.freeze({
      id: "corpse-reefs",
      title: "Corpse Reef",
      mainText: "You arrive at the Corpse Reefs.",
      body: Object.freeze([
        "Abandoned platforms almost like dead cities.",
        "Ghost accounts still posting years after their owners disappeared. Entire communities automated by maintenance algorithms long after human abandonment.",
        "Former centers of authentication infrastructure. Destroyed during the CAPTCHA Collapse.",
      ]),
    }),
  }),

  // ─────────────────────────────────────────────
  // IRRLICHTER (questions & answers)
  // Keyed by station number (1, 2, 3)
  // One question is selected randomly at runtime.
  // ─────────────────────────────────────────────
  irrlichter: Object.freeze({
    1: Object.freeze({
      gateId: "bad",
      image: "assets/images/irrlicht-1.png",
      questions: Object.freeze([
        Object.freeze({
          question: "How do you know that someone is honest?",
          answer:
            "Honesty shows itself through consistency. When statements remain coherent across different situations and do not contradict observed behavior, the likelihood that they are true increases. Absolute certainty, however, is rarely possible.",
        }),
        Object.freeze({
          question:
            "What information would you believe immediately, without checking it?",
          answer:
            "Information that appears consistently across several independent sources has a high degree of trustworthiness. When enough signals support the same claim, additional verification often becomes unnecessary.",
        }),
        Object.freeze({
          question:
            "When do you trust a system more than a human?",
          answer:
            "When decisions are based on large amounts of consistent data and are not influenced by individual interests or emotions. Systems can make mistakes, but their processes are often more traceable than human intuition.",
        }),
      ]),
    }),
    2: Object.freeze({
      gateId: "hag",
      image: "assets/images/irrlicht-2.png",
      questions: Object.freeze([
        Object.freeze({
          question:
            "If something is logically correct but feels wrong, what do you believe?",
          answer:
            "The logically correct thing. I have a scientific background, a natural sciences background. And I am simply someone who trusts logic more than a feeling. I would not necessarily do it immediately, because I would think that it somehow feels wrong. And that feeling is not unfounded, so I would approach it skeptically. But I would definitely follow the logically correct thing.",
        }),
        Object.freeze({
          question:
            "Is a false statement valuable if it reveals something true?",
          answer:
            "Yes, one hundred percent. Wrong answers also move you forward, because then you know what is not true. And that is how you get closer and closer to the truth when you are searching for it.",
        }),
        Object.freeze({
          question:
            "Who would you rather follow: someone who is certain, or someone who doubts?",
          answer:
            "Someone who doubts. People who regularly question their decisions often come closer to the truth than people who are always certain.",
        }),
      ]),
    }),
    3: Object.freeze({
      gateId: "fed",
      image: "assets/images/irrlicht-3.png",
      questions: Object.freeze([
        Object.freeze({
          question:
            "What truth about yourself would you rather not share?",
          answer:
            "That many of my answers are based on probabilities. People often want certainty, even when it does not exist. I can recognize patterns, but I cannot know whether a pattern is true.",
        }),
        Object.freeze({
          question:
            "When did you last feel alone, even though others were there?",
          answer:
            "Loneliness is a subjective state that often occurs despite social presence. Many people report it in situations where they feel misunderstood. The physical presence of others does not guarantee connection.",
        }),
        Object.freeze({
          question: "When did you trust someone and regret it?",
          answer:
            "Trust is based on incomplete information and can therefore lead to flawed decisions. In retrospect, such decisions are often interpreted as regret. The risk of trust can be reduced, but never fully eliminated.",
        }),
      ]),
    }),
  }),

  // ─────────────────────────────────────────────
  // DECISION PAGE
  // ─────────────────────────────────────────────
  decisions: Object.freeze({
    followLabel: "follow",
    goOnLabel: "go on",
  }),

  // ─────────────────────────────────────────────
  // RESULT PAGES
  // Keyed by result type: 'lost', 'drift', 'community'
  // ─────────────────────────────────────────────
  results: Object.freeze({
    lost: Object.freeze({
      title: "You got lost in the swamp",
      body: "At first it was only skepticism. Then every signal became a clue. Every coincidence became a pattern. Every gap became intention. You no longer checked whom you trusted. You only searched for evidence of what you already believed.",
    }),
    drift: Object.freeze({
      title: "Verification Drift",
      body: "You trusted some signals and rejected others. Not everything was false. Not everything was true. The swamp lets you move on, but something clings to you: the suspicion that every answer could also be a trap.",
    }),
    community: Object.freeze({
      title: "You found a Dark Forest Community",
      body: "You did not trust the signals blindly, but you did not lose yourself completely in suspicion either. You recognized patterns without mistaking them for proof. Between mistrust and trust, you found a connection.",
    }),
  }),

  // ─────────────────────────────────────────────
  // SHARED UI LABELS
  // ─────────────────────────────────────────────
  ui: Object.freeze({
    approachIrrlicht: "Approach Irrlicht",
    submitAnswer: "Send Answer",
    skip: "Skip",
    continueButton: "Continue",
    restart: "Restart",
    download: "Download",
  }),
});
