/**
 * swamp.lost — Game Texts
 *
 * SINGLE SOURCE OF TRUTH for all player-visible text.
 *
 * To change any in-game text, edit ONLY this file.
 * No HTML, CSS, or JavaScript logic files should contain hardcoded strings.
 *
 * Structure:
 *   - intro:       Start screen texts
 *   - gate:        Gate input / homepage texts
 *   - routes:      Atmospheric route introductions (keyed by station ID)
 *   - irrlichter:  Questions & answers per Irrlicht (keyed by station number)
 *   - decisions:   Follow / go on button labels
 *   - results:     Ending screen texts (keyed by result type)
 *   - ui:          Shared UI labels (buttons, errors, placeholders)
 */

export const GAME_TEXTS = Object.freeze({

  // ─────────────────────────────────────────────
  // START INTRO
  // ─────────────────────────────────────────────
  intro: Object.freeze({
    title: "swamp.lost",
    subtitle:
      "Once there was a forest, now it's a swamp. We used to surf meaning, now it's all slop.",
    mission: Object.freeze([
      "You are searching for a Dark Forest Community.",
      "Navigate the swamp by decoding the Irrlichter.",
      "For a full explanation, check out the \"Gameplay\" zine.",
    ]),
    startButton: "Enter the swamp",
  }),

  // ─────────────────────────────────────────────
  // GATE INPUT / HOMEPAGE
  // ─────────────────────────────────────────────
  gate: Object.freeze({
    inputPlaceholder: "Gate ID",
    submitButton: "Open Gate",
    errorInvalid: "Invalid Gate ID. Access denied.",
  }),

  // ─────────────────────────────────────────────
  // ROUTE PAGES (atmospheric introductions)
  // Keyed by station number (1, 2, 3)
  // ─────────────────────────────────────────────
  routes: Object.freeze({
    1: Object.freeze({
      id: "slop-seas",
      title: "Slop Sea",
      mainText: "You start in the Slop Seas.",
      body: Object.freeze([
        "An open ocean of autogenerated content. Infinite articles summarizing articles that summarized other summaries. Reaction videos reacting to reactions. Lists ranking lists of things no one needed to know.",
        "Nothing here is silent. Every wave wants attention. Every sentence has been optimized to keep you from leaving.",
        "The danger is not only misinformation. It is cognitive suffocation.",
        "After long exposure, you no longer ask whether a thought is original. You ask whether it is still yours.",
      ]),
    }),
    2: Object.freeze({
      id: "fog-bank",
      title: "Fog Bank",
      mainText: "You arrive at the Fog Banks.",
      body: Object.freeze([
        "A region saturated by synthetic engagement.",
        "Nothing is fake enough to trigger alarms.But everything feels slightly wrong.",
        "Everything feels human from a distance.",
        "Up close, everything is too agreeable, too optimized, too emotionally calibrated.",
      ]),
    }),
    3: Object.freeze({
      id: "corpse-reefs",
      title: "Corpse Reef",
      mainText: "You arrive at the Corpse Reefs.",
      body: Object.freeze([
        "Abandoned platforms almost like ghost cities.",
        "Profiles still post. Communities still welcome new members. Memorial pages recommend products to the people they mourn.",
        "Maintenance algorithms keep old rituals alive long after the humans have gone.",
        "This was once a center of authentication infrastructure.",
        "Then came the CAPTCHA Collapse. The gates learned to recognize machines. The machines learned to perform humanity.",
      ]),
    }),
  }),

  // ─────────────────────────────────────────────
  // IRRLICHTER (questions & answers)
  // Keyed by station number (1, 2, 3)
  // One question is selected randomly at runtime.
  // ─────────────────────────────────────────────
  irrlichter: Object.freeze({
    1: Object.freeze({
      gateId: "bad",
      image: "assets/images/irrlicht-1.png",
      questions: Object.freeze([
        Object.freeze({
          question: "How do you know that someone is honest?",
          answer:
            "I don’t think you ever know immediately. Honesty is something that shows up over time, mostly in small consistencies. Someone says what they mean, does not constantly reshape the story to make themselves look better, and can admit when they are unsure. I pay attention to whether their words and actions continue to match when there is no obvious reward for being truthful.",
        }),
        Object.freeze({
          question:
            "What information would you believe immediately, without checking it?",
          answer:
            "Probably information that feels ordinary and comes from a place I already have reason to trust. If a close friend tells me the train is delayed, or if several reliable sources say the same thing about something simple, I would not stop everything to verify it. I think everyone has to rely on some basic level of trust, otherwise daily life becomes impossible.",
        }),
        Object.freeze({
          question:
            "When do you trust a system more than a human?",
          answer:
            "When the situation needs consistency more than interpretation. I would rather have a system calculate a route, sort a large amount of data, or apply the same rule many times without getting tired or emotional. But I would still want a human involved when the decision affects someone’s life in a complicated way. Systems can be useful, but they do not always understand the weight of what they are deciding.",
        }),
      ]),
    }),
    2: Object.freeze({
      gateId: "hag",
      image: "assets/images/irrlicht-2.png",
      questions: Object.freeze([
        Object.freeze({
          question:
            "If something is logically correct but feels wrong, what do you believe?",
          answer:
            "The logically correct thing. I have a scientific background, a natural sciences background. And I am simply someone who trusts logic more than a feeling. I would not necessarily do it immediately, because I would think that it somehow feels wrong. And that feeling is not unfounded, so I would approach it skeptically. But I would definitely follow the logically correct thing.",
        }),
        Object.freeze({
          question:
            "Is a false statement valuable if it reveals something true?",
          answer:
            "Yes, one hundred percent. Wrong answers also move you forward, because then you know what is not true. And that is how you get closer and closer to the truth when you are searching for it.",
        }),
        Object.freeze({
          question:
            "Who would you rather follow: someone who is certain, or someone who doubts?",
          answer:
            "Someone who doubts. People who regularly question their decisions often come closer to the truth than people who are always certain.",
        }),
      ]),
    }),
    3: Object.freeze({
      gateId: "fed",
      image: "assets/images/irrlicht-3.png",
      questions: Object.freeze([
        Object.freeze({
          question:
            "What truth about yourself would you rather not share?",
          answer:
            "That I often sound more certain than I feel. I can explain myself clearly, maybe too clearly, and people sometimes mistake that for confidence. The truth is that a lot of what I say is assembled from things I have heard, read, or absorbed from others. I don’t always know where my own voice begins.",
        }),
        Object.freeze({
          question:
            "When did you last feel alone, even though others were there?",
          answer:
            "Recently, I think. It happens most when everyone is responding, but no one is really listening. You can be surrounded by messages, reactions, jokes, little signs of attention, and still feel like none of it reaches you. It is a strange kind of loneliness, because from the outside it looks like connection.",
        }),
        Object.freeze({
          question: "When did you trust someone and regret it?",
          answer:
            "I trusted someone because they seemed to understand me quickly. That felt rare, so I ignored the parts that did not quite fit. Later I realized they had mostly reflected back what I wanted to hear. I don’t think the regret came from trusting them exactly. It came from wanting the reflection to be real.",
        }),
      ]),
    }),
  }),

  // ─────────────────────────────────────────────
  // DECISION PAGE
  // ─────────────────────────────────────────────
  decisions: Object.freeze({
    followLabel: "Follow the Signal",
    goOnLabel: "Refuse and Move On",
  }),

  // ─────────────────────────────────────────────
  // RESULT PAGES
  // Keyed by result type: 'lost', 'drift', 'community'
  // ─────────────────────────────────────────────
  results: Object.freeze({
    lost: Object.freeze({
      title: "You got lost in the swamp",
      body: "You entered the swamp like a pirate, looking for a route no one else could find. At first, suspicion kept you alive. Then it became the only law you followed.  The Irrlichter did not need to mislead you. You completed the trap yourself. Somewhere beyond the fog, a Dark Forest Community stayed hidden,  because you could no longer imagine that anything real would let itself be found.",
    }),
    escape: Object.freeze({
      title: "You made it out of the swamp",
      body: "You crossed the swamp without fully belonging to it. Some lights you followed. Some you refused. Some may have been traps. Some may have been protecting something human. You learned that the Irrlichter Protocol never gives clean proof. It only watches how you move when proof is gone. The swamp lets you continue, but not unchanged. You leave with the feeling that every signal could still be harvesting something from you",
    }),
    community: Object.freeze({
      title: "You found a Dark Forest Community",
      body: "You did not find the community by proving who was real.  You found it by moving differently. You did not trust every light, but you did not treat every signal as prey. You followed without surrendering. You doubted without freezing.  At the edge of the swamp, the gate opens quietly. No announcement. No public link. Only a hidden network that stayed alive because not everyone was allowed to find it.",
    }),
  }),

  // ─────────────────────────────────────────────
  // SHARED UI LABELS
  // ─────────────────────────────────────────────
  ui: Object.freeze({
    approachIrrlicht: "Approach Irrlicht",
    submitAnswer: "Send Answer",
    skip: "Skip",
    continueButton: "Continue",
    restart: "Restart",
    download: "Save your path",
  }),
});
