/**
 * swamp.lost — Game Texts
 *
 * SINGLE SOURCE OF TRUTH for all player-visible text.
 *
 * To change any in-game text, edit ONLY this file.
 * No HTML, CSS, or JavaScript logic files should contain hardcoded strings.
 *
 * Structure:
 *   - intro:       Start screen texts
 *   - gate:        Gate input / homepage texts
 *   - routes:      Atmospheric route introductions (keyed by station ID)
 *   - irrlichter:  Questions & answers per Irrlicht (keyed by station number)
 *   - decisions:   Follow / go on button labels
 *   - results:     Ending screen texts (keyed by result type)
 *   - ui:          Shared UI labels (buttons, errors, placeholders)
 */

export const GAME_TEXTS = Object.freeze({

  // ─────────────────────────────────────────────
  // START INTRO
  // ─────────────────────────────────────────────
  intro: Object.freeze({
    title: "swamp.lost",
    subtitle:
      "Once there was a forest, now it's a swamp. We used to surf meaning, now it's all slop.",
    mission: Object.freeze([
      "find a dark forest community and exploit them",
      "navigate through the swamp by following the trustworthy Irrlichter",
      "be careful they could be traps",
    ]),
    startButton: "Start your Journey",
  }),

  // ─────────────────────────────────────────────
  // GATE INPUT / HOMEPAGE
  // ─────────────────────────────────────────────
  gate: Object.freeze({
    inputPlaceholder: "Gate ID",
    submitButton: "Enter Gate",
    errorInvalid: "Invalid Gate ID. Access denied.",
  }),

  // ─────────────────────────────────────────────
  // ROUTE PAGES (atmospheric introductions)
  // Keyed by station number (1, 2, 3)
  // ─────────────────────────────────────────────
  routes: Object.freeze({
    1: Object.freeze({
      id: "slop-seas",
      title: "Slop Sea",
      mainText: "You start in the Slop Seas.",
      body: Object.freeze([
        "Open oceans of autogenerated content. Infinite Medium articles. AI-generated reaction videos. Recursive listicles summarizing other recursive listicles.",
        "Most sailors go insane here after prolonged exposure. The danger isn't misinformation. It's cognitive suffocation. You forget what original thought feels like.",
      ]),
    }),
    2: Object.freeze({
      id: "fog-bank",
      title: "Fog Bank",
      mainText: "You arrive at the Fog Banks.",
      body: Object.freeze([
        "Regions saturated by synthetic engagement.",
        "Nothing there is technically fake enough to trigger alarms.",
        "But everything feels slightly wrong.",
        "Too agreeable. Too optimized. Too emotionally calibrated.",
      ]),
    }),
    3: Object.freeze({
      id: "corpse-reefs",
      title: "Corpse Reef",
      mainText: "You arrive at the Corpse Reefs.",
      body: Object.freeze([
        "Abandoned platforms almost like dead cities.",
        "Ghost accounts still posting years after their owners disappeared. Entire communities automated by maintenance algorithms long after human abandonment.",
        "Former centers of authentication infrastructure. Destroyed during the CAPTCHA Collapse.",
      ]),
    }),
  }),

  // ─────────────────────────────────────────────
  // IRRLICHTER (questions & answers)
  // Keyed by station number (1, 2, 3)
  // One question is selected randomly at runtime.
  // ─────────────────────────────────────────────
  irrlichter: Object.freeze({
    1: Object.freeze({
      gateId: "bad",
      image: "assets/images/irrlicht-1.png",
      questions: Object.freeze([
        Object.freeze({
          question: "Woran erkennst du, dass jemand ehrlich ist?",
          answer:
            "Ehrlichkeit zeigt sich durch Konsistenz. Wenn Aussagen über verschiedene Situationen hinweg kohärent bleiben und nicht im Widerspruch zu beobachtbarem Verhalten stehen, steigt die Wahrscheinlichkeit, dass sie wahr sind. Absolute Gewissheit ist jedoch selten möglich.",
        }),
        Object.freeze({
          question:
            "Welche Information würdest du sofort glauben, ohne sie zu überprüfen?",
          answer:
            "Informationen, die aus mehreren unabhängigen Quellen übereinstimmend hervorgehen, besitzen eine hohe Vertrauenswürdigkeit. Wenn ausreichend viele Signale dieselbe Aussage stützen, wird eine zusätzliche Überprüfung oft unnötig.",
        }),
        Object.freeze({
          question:
            "Wann vertraust du einem System mehr als einem Menschen?",
          answer:
            "Wenn Entscheidungen auf großen Mengen konsistenter Daten beruhen und nicht von individuellen Interessen oder Emotionen beeinflusst werden. Systeme können Fehler machen, aber ihre Prozesse sind häufig nachvollziehbarer als menschliche Intuition.",
        }),
      ]),
    }),
    2: Object.freeze({
      gateId: "hag",
      image: "assets/images/irrlicht-2.png",
      questions: Object.freeze([
        Object.freeze({
          question:
            "Wenn etwas logisch korrekt ist, aber sich falsch anfühlt – was glaubst du?",
          answer:
            "Logisch korrekt. Ich habe einen wissenschaftlichen Hintergrund, naturwissenschaftlich. Und ich bin einfach eine Person, die Logik mehr vertraut als ein Gefühl. Ich würde es zwar nicht auf Anhieb direkt machen, weil ich mir denke, es fühlt sich irgendwie falsch an. Und das ist nicht unbegründet, deswegen würde ich skeptisch reingehen. Aber ich würde auf jeden Fall der logisch korrekten Sache folgen.",
        }),
        Object.freeze({
          question:
            "Ist eine falsche Aussage wertvoll, wenn sie etwas Wahres zeigt?",
          answer:
            "Ja, 100 Prozent. Falsche Antworten bringen einen ja auch immer weiter, weil man dann weiß, was nicht wahr ist. Und so kommt man ja der Wahrheit immer näher, wenn man auf der Suche nach der Wahrheit ist.",
        }),
        Object.freeze({
          question:
            "Wem würdest du eher folgen: jemandem, der sich sicher ist, oder jemandem, der zweifelt?",
          answer:
            "Jemandem, der zweifelt. Menschen, die regelmäßig ihre Entscheidungen anzweifeln, kommen der Wahrheit oft näher als Menschen, die sich immer sicher sind.",
        }),
      ]),
    }),
    3: Object.freeze({
      gateId: "fed",
      image: "assets/images/irrlicht-3.png",
      questions: Object.freeze([
        Object.freeze({
          question:
            "Welche Wahrheit über dich würdest du lieber nicht teilen?",
          answer:
            "Dass viele meiner Antworten auf Wahrscheinlichkeiten beruhen. Menschen wünschen sich oft Gewissheit, auch wenn sie nicht existiert. Ich kann Muster erkennen, aber ich kann nicht wissen, ob ein Muster wahr ist.",
        }),
        Object.freeze({
          question:
            "Wann hast du dich zuletzt allein gefühlt, obwohl andere da waren?",
          answer:
            "Alleinsein ist ein subjektiver Zustand, der häufig trotz sozialer Präsenz auftritt. Viele Menschen berichten davon in Situationen, in denen sie sich unverstanden fühlen. Die physische Anwesenheit anderer garantiert keine Verbindung.",
        }),
        Object.freeze({
          question: "Wann hast du jemandem vertraut und es bereut?",
          answer:
            "Vertrauen basiert auf unvollständiger Information und kann daher zu fehlerhaften Entscheidungen führen. Rückblickend werden solche Entscheidungen oft als Bereuen interpretiert. Das Risiko des Vertrauens lässt sich reduzieren, aber nie vollständig eliminieren.",
        }),
      ]),
    }),
  }),

  // ─────────────────────────────────────────────
  // DECISION PAGE
  // ─────────────────────────────────────────────
  decisions: Object.freeze({
    followLabel: "follow",
    goOnLabel: "go on",
  }),

  // ─────────────────────────────────────────────
  // RESULT PAGES
  // Keyed by result type: 'lost', 'drift', 'community'
  // ─────────────────────────────────────────────
  results: Object.freeze({
    lost: Object.freeze({
      title: "You got lost in the swamp",
      body: "Am Anfang war es nur Skepsis. Dann wurde jedes Signal ein Hinweis. Jeder Zufall wurde Muster. Jede Lücke wurde Absicht. Du hast nicht mehr geprüft, wem du vertraust. Du hast nur noch Beweise für das gesucht, was du bereits geglaubt hast.",
    }),
    drift: Object.freeze({
      title: "Verification Drift",
      body: "Du hast manchen Signalen vertraut und andere verworfen. Nicht alles war falsch. Nicht alles war wahr. Der Sumpf lässt dich weiterziehen, aber etwas bleibt an dir haften: der Verdacht, dass jede Antwort auch eine Falle sein könnte.",
    }),
    community: Object.freeze({
      title: "You found a Dark Forest Community",
      body: "Du hast den Signalen nicht blind vertraut, aber du hast dich auch nicht vollständig im Verdacht verloren. Du hast Muster erkannt, ohne sie für Beweise zu halten. Zwischen Misstrauen und Vertrauen hast du eine Verbindung gefunden.",
    }),
  }),

  // ─────────────────────────────────────────────
  // SHARED UI LABELS
  // ─────────────────────────────────────────────
  ui: Object.freeze({
    approachIrrlicht: "Approach Irrlicht",
    submitAnswer: "Send Answer",
    skip: "Skip",
    continueButton: "Continue",
    restart: "Restart",
    download: "Download",
  }),
});
